on:
  push:
  pull_request:
    branches:
      - master

name: render

jobs:
  render_deploy:

    runs-on: ubuntu-latest
    container: bioconductor/bioconductor_docker:bioc2020

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - uses: actions/checkout@v1

      - name: Initialise renv
        run: |
          install.packages(c('renv', 'BiocManager'))
        shell: Rscript {0}

      - name: Cache renv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-r-1-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ runner.os }}-r-1-

      # This lets us augment with additional dependencies
      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"

      - name: Install dependencies
        run: |
          options(repos = c(CRAN = "https://cran.r-project.org"))
          BiocManager::repositories()
          remotes::install_deps(dependencies = TRUE, repos = BiocManager::repositories(), Ncpu = 2L)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Render site
        run: |
          install.packages('rmarkdown', Ncpus = 2L)
          rmarkdown::render(input = "index.Rmd")
        shell: Rscript {0}

      - name: Prepare files to deploy
        run: |
          mkdir _site
          cp -r img libs my-theme.css index.html _site/

      # deploy needs rsync? Seems so.
      - name: Install deploy dependencies
        #if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          apt-get update && apt-get -y install rsync

      - name: Deploy 🚀
        #if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: _site # The folder the action should deploy.
